---
title: "PS03: Data wrangling with dplyr"
output: html_document
author: Alex Rogers
---

```{r}

library(dplyr)
library(ggplot2)
library(nycflights13)

```
### Notes

This is where I'm keeping my notes and code for the data wrangling section of modern dive.


```{r}

portland_flights <- flights |> 
  filter(dest == "PDX")
View(portland_flights)


```

```{r}
btv_sea_flights_all <- flights |> 
  filter(origin == "JFK" & (dest == "BTV" | dest == "SEA") & month >= 10)
View(btv_sea_flights_all)


```

```{r}

not_BTV_SEA <- flights |> 
  filter(!(dest == "BTV" | dest == "SEA"))
View(not_BTV_SEA)


```


```{r}

many_airports <- flights |> 
  filter(dest == "SEA" | dest == "SFO" | dest == "PDX" | dest == "BTV" | dest == "BDL")
View(many_airports)

```

```{r}
many_airports <- flights |> 
  filter(dest %in% c("SEA", "SFO", "PDX", "BTV", "BDL"))
View(many_airports)


```

### 3.3, summarize variables

```{r}

summary_temp <- weather |> 
  summarize(mean = mean(temp, na.rm = TRUE), 
            std_dev = sd(temp, na.rm = TRUE))
summary_temp

```


The code in chunk 7 (which starts with summary_temp) is confusing for me to read. 

### 3.4 group by rows


```{r}

summary_monthly_temp <- weather |> 
  group_by(month) |> 
  summarize(mean = mean(temp, na.rm = TRUE),
            std_dev = sd(temp, na.rm = TRUE))
summary_monthly_temp

```

```{r}
diamonds
```

```{r}

diamonds |> 
  group_by(cut)

```


```{r}

diamonds |> 
  group_by(cut) |> 
  summarize(avg_price = mean(price))


```


```{r}
diamonds |> 
group_by(cut) |> 
ungroup()


```

```{r}

by_origin <- flights |> 
  group_by(origin) |> 
  summarize(count = n())
by_origin


```

### 3.4.1 Grouping by more than 1 variable

```{r}

by_origin_monthly <- flights |> 
  group_by(origin, month) |> 
  summarize(count = n())
by_origin_monthly

```

